export ofs_bench_ex=../cmake-build-relwithdebinfo/src/bench/ofs
export append_ofs_multi_bench_ex=../cmake-build-relwithdebinfo/src/bench/append-ofs-multi
export append_ofs_bench_ex=../cmake-build-relwithdebinfo/src/bench/append-ofs
export osm_bench_ex=../cmake-build-relwithdebinfo/src/bench/osm
export append_osm_bench_ex=../cmake-build-relwithdebinfo/src/bench/append-osm
export omap_bench_ex=../cmake-build-relwithdebinfo/src/bench/omap
export hdd_base_path=/mnt/hdd1/tests/cache
export ssd_base_path=~/ssdmount/scratch/datadir/ssd/cache
#export ssd_base_path=/home/cc/dev/tmp/deleteme/ssd/testdata
export num_runs=1
export n=22
export vs=(128)
export v=128
export lvls=(12 10 8)
export lvl=8
append_ns=$(seq 18 1 22)
export append_ns
export append_s=2
export append_lf=1
