#include using cmake -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake
#INCLUDE(CMakeForceCompiler) #Disables checks
#SET(CMAKE_SYSTEM_NAME Generic)
#Generic removes -rdynamic from linker, which llvm-ld doesn't support

SET(CMAKE_C_COMPILER clang-16)
SET(CMAKE_CXX_COMPILER clang++-16)
#SET(CMAKE_RANLIB "/usr/bin/llvm-ranlib-16" CACHE INTERNAL STRING)
#SET(CMAKE_AR "/usr/bin/llvm-ar-16" CACHE INTERNAL STRING)
#
#SET(CMAKE_LINKER "/usr/bin/ld.lld-16" CACHE INTERNAL STRING)
##SET(CMAKE_C_LINKER "/usr/bin/llvm-ld")
##SET(CMAKE_CXX_LINKER "/usr/bin/llvm-ld")
#
#SET(CMAKE_C_LINK_EXECUTABLE "/usr/bin/ld.lld-16 <OBJECTS> -o  <TARGET> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES>")
#SET(CMAKE_CXX_LINK_EXECUTABLE "/usr/bin/ld.lld-16 <OBJECTS> -o  <TARGET> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <LINK_LIBRARIES>")

SET(CMAKE_FIND_ROOT_PATH /usr/bin)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
